alias nvidia nvidia-current
alias nvidia-modeset nvidia-current-modeset
alias nvidia-drm nvidia-current-drm
alias nvidia-uvm nvidia-current-uvm
alias nvidia-peermem nvidia-current-peermem

blacklist nouveau
options nouveau modeset=0
