[Greeter]
background=/usr/share/backgrounds/puresteel/wallpaper.png
background-color=#08111d
draw-user-backgrounds=false
logo=/usr/share/pixmaps/puresteel-installer.png
theme-name=Adwaita-dark
icon-theme-name=Puresteel
font-name=Sans 10
enable-hidpi=auto
show-hostname=true
show-clock=true
show-power=true
