[Icon Theme]
Name=Puresteel
Comment=Puresteel OS branding icons
Inherits=breeze
Directories=places/16,places/22,places/24,places/32,places/64,places/96

[places/16]
Size=16
Type=Fixed
Context=Places

[places/22]
Size=22
Type=Fixed
Context=Places

[places/24]
Size=24
Type=Fixed
Context=Places

[places/32]
Size=32
Type=Fixed
Context=Places

[places/64]
Size=64
Type=Fixed
Context=Places

[places/96]
Size=96
Type=Fixed
Context=Places
