Window.SetBackgroundTopColor(0.012, 0.035, 0.075);
Window.SetBackgroundBottomColor(0.006, 0.016, 0.032);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.opacity_angle = 0;

fun refresh_callback ()
{
    logo.sprite.SetX(Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
    logo.sprite.SetY(Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2);

    logo.opacity_angle += ((2 * 3.14) / 60) * 0.35;
    opacity = (Math.Cos(logo.opacity_angle) + 1) / 2;
    opacity = opacity * 0.18 + 0.82;
    logo.sprite.SetOpacity(opacity);
}

Plymouth.SetRefreshFunction(refresh_callback);
